### ISSUE TITLE
Connection BME280 to PC(Windows) 

### ISSUE THREAD

**Issue by VoidVii** [ludiazv/node-red-contrib-bme280#9]
Hello,

im looking for a way to connect a BME280 via USB-I2C to my PC (Windows). 
My idea was to use something like this : 
https://www.amazon.de/I2C-MP-USB-I%C2%B2C-USB-Adapter-Evaluations-Board-SMD/dp/B07VSMW6P6/ref=pd_lpo_2?pd_rd_i=B07VSMW6P6&psc=1

BME280 -> I2C-USB-Adapter -> PC -> Node-Red -> node-red-contrib-bme280

Did someone tried something like this already?
I dont need a controller since the node provides the code right?
Could this work out the way i described the idea?

best regards

**Comment by ludiazv** [comment]
Hi,
   This node do not support the configuration above you describe as the node requires linux and direct access to I2C interface.

  If you need to connect a I2C device to a PC in my opinion the cheapest and possible the easiest way is to use a arduino board nano or wemos d1 or similar program it with a minimal bme280 sketch that send over serial the measures periodically and node-red serial node to read those values.

**Comment by VoidVii** [comment]
Thank you very much for the information.
